name: CI
on: [push]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: shards install
      - run: crystal tool format --check
      - name: Build ameba
        run: |
          mkdir -p bin
          crystal build --no-debug lib/ameba/bin/ameba.cr -o bin/ameba
      - run: bin/ameba

  spec:
    name: Spec
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: shards install
      - run: crystal spec --order random

  examples:
    name: Examples
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Compile examples
        run: |
          for f in examples/*.cr; do
            echo "::group::$f"
            crystal build --no-codegen "$f"
            echo "::endgroup::"
          done
