name: CI
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: shards install
      - run: crystal tool format --check
      - name: Build ameba
        run: |
          mkdir -p bin
          crystal build --no-debug lib/ameba/bin/ameba.cr -o bin/ameba
      - run: bin/ameba

  spec:
    name: Spec
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: shards install
      - run: crystal spec --order random
