name: CI
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-ameba/github-action@v0.2.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: crystal-lang/install-crystal@v1
      - run: crystal tool format && git diff --exit-code

  spec:
    name: Spec
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
      - run: shards install --ignore-crystal-version
      - run: crystal spec --order random
